config/routes.rb
Rails.application.routes.draw do

#=============================================================================
# ================================ ADMIN =====================================
#=============================================================================
  namespace :admin do

    controller :users do
    end
    resources :users

    controller :empreendimentos do
      post '/empreendimentos/deletar_foto/:id' => :deletar_foto, as: :empreendimentos_deletar_foto
    end
    resources :empreendimentos

    controller :categorias do
    end
    resources :categorias

    controller :contatos do
    end
    resources :contatos

    controller :contato_assuntos do
    end
    resources :contato_assuntos

    controller :vagas_pretendidas do
    end
    resources :vagas_pretendidas

    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

#=============================================================================
# ================================ PÚBLICO ===================================
#=============================================================================

  devise_for :users, :controllers => { registrations: 'registrations',
                                        :omniauth_callbacks => "callbacks" }



  authenticated :user do
    root 'admin/pages#home', as: :authenticated_root
  end

  controller :users do
    post "users/novo_contato" => :novo_contato
  end
  resources :users, only: [:new, :create]

  controller :empreendimentos do
  end
  resources :empreendimentos, only: [:index, :show]

  controller :contatos do
  end
  resources :contatos, only: [:index, :new, :create]

  controller :enderecos do
    post "enderecos/att_endereco" => :att_endereco
  end

  controller :pages do
    get '/home' => :home
    get '/sac' => :sac
    get '/trabalhe_conosco' => :trabalhe_conosco
    get '/dicas' => :dicas
    get '/minha_casa_minha_vida' => :minha_casa_minha_vida
  end 

  root 'pages#home'

end

app/views/shared/_footer.html.erb
<div class="page-footer">
	
    <%= render '/pages/mapa' %>
    <%= render '/pages/institucional' %>
  <div class="container">
    <div class="copyright">
      <b>
      <p style="text-align: center;">
       Copyright ® <%= Date.today.year %> | Giardino | 
      </p>
      </b>
    </div>
  </div>
</div>

app/views/shared/_form_error.html.erb
<% if object.errors.any? %>

<div class="row">
  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">OPS <span class="badge red white-text"><%= object.errors.size %></span></span>
        <% object.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
      <div class="card-action">
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/shared/_form_success.html.erb
<div class="row">
  <div class="col s12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title">Cadastro realizado com sucesso <span class="badge green white-text"><%= 3 %></span></span>
          <p><%= user.nome %></p>
          <p><%= user.email %></p>
          <p><%= user.celular unless user.celular.blank? %></p>
          <p><%= user.mensagem unless user.mensagem.blank? %></p>
      </div>
      <div class="card-action">
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<nav class="nav_top">
          <img class="brand-logo" src="/images/logos/logo.png" style="max-width: 64px; padding: 2px;" >
  <div class="nav-wrapper container">
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
    <ul class="left hide-on-med-and-down">
        <li><%= link_to "HOME", home_path, class: "#{'active' if current_page? home_path}" %></li>
        <li><a class="dropdown-button" data-activates="dropdown1">FALE CONOSCO<i class="material-icons right">arrow_drop_down</i></a></li>
    </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to "HOME", home_path, class: "#{'active' if current_page? home_path}" %></li>
        <li><%= link_to "LOGIN", new_user_session_path, class: "#{'active' if current_page? new_user_session_path}" if current_user.blank? %></li>
        <li><%= link_to "SAC", sac_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
        <li><%= link_to "TRABALHE CONOSCO", sac_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
        <li><%= link_to "DÚVIDAS E SUGESTÕES", sac_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
        <li><div class="divider"></div></li>
        <li><%= link_to "SAIR", destroy_user_session_path unless current_user.blank? %></li>
      </ul>

    <ul class="right hide-on-med-and-down">
      <% if current_user %>
              <li>
                <%= link_to "#{image_tag(current_user.image_to, class: 'btn btn-large btn-floating', style: 'padding-top: 7px; background-color: #273249; border: 4px solid #273249;')}".html_safe, admin_root_path, class: "btn btn-large btn-floating pulse", style: "background-color: #fff; border: 2px solid #273249;" %>
                <li><%= link_to("Sair <i class='material-icons'>exit_to_app</i>".html_safe, destroy_user_session_path, :method => :delete, style: "display: inline-flex;") %></li>
              </li>
        <% else %>
        <li><%= link_to "login <i class='material-icons' style='transform: rotate(180deg);'>exit_to_app</i>".html_safe, new_user_session_path, style: "display: inline-flex;", class: "#{'active' if current_page? new_user_session_path}" %></li>
        <% end %>
    </ul>
  </div>
</nav>

<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  <li><%= link_to "SAC", sac_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
  <li><%= link_to "TRABALHE CONOSCO", trabalhe_conosco_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
  <li><%= link_to "DÚVIDAS E SUGESTÕES", dicas_path, class: "#{'active' if current_page? sac_path}", style: "color: black; border: none;" %></li>
</ul>


<style type="text/css">
  a.active{

        text-shadow: 0 0 2px rgba(255, 255, 255, 1);
        background: transparent;
        border-bottom: 3px #fff solid;
        margin-bottom: -5px;
  }
</style>

      