config/routes.rb
Rails.application.routes.draw do

#=============================================================================
# ================================ ADMIN =====================================
#=============================================================================
  namespace :admin do

    controller :users do
    end
    resources :users

    controller :empreendimentos do
      post '/empreendimentos/deletar_foto/:id' => :deletar_foto, as: :empreendimentos_deletar_foto
    end
    resources :empreendimentos

    controller :categorias do
    end
    resources :categorias

    controller :contatos do
    end
    resources :contatos

    controller :contato_assuntos do
    end
    resources :contato_assuntos

    controller :vagas_pretendidas do
    end
    resources :vagas_pretendidas

    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

#=============================================================================
# ================================ PÚBLICO ===================================
#=============================================================================

  devise_for :users, :controllers => { registrations: 'registrations',
                                        :omniauth_callbacks => "callbacks" }



  authenticated :user do
    root 'admin/pages#home', as: :authenticated_root
  end

  controller :users do
    post "users/novo_contato" => :novo_contato
  end
  resources :users, only: [:new, :create]

  controller :empreendimentos do
  end
  resources :empreendimentos, only: [:index, :show]

  controller :contatos do
  end
  resources :contatos, only: [:index, :new, :create]

  controller :enderecos do
    post "enderecos/att_endereco" => :att_endereco
  end

  controller :pages do
    get '/home' => :home
    get '/sac' => :sac
    get '/trabalhe_conosco' => :trabalhe_conosco
    get '/dicas' => :dicas
    get '/minha_casa_minha_vida' => :minha_casa_minha_vida
  end 

  root 'pages#home'

end

app/models/categoria.rb
class Categoria < ApplicationRecord

  validates :nome, presence: true

  has_many :empreendimentos

  def self.to_select
  	Categoria.all.collect { |c| [c.nome, c.id] }
  end

end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::AdminController

  before_action :set_categoria, only: [:show, :edit, :update]

  # GET /categorias
  def index
    conditions = []
    conditions << "categorias.id = #{params[:id]}" unless params[:id].blank?
    conditions << "UPPER(categorias.nome) LIKE '%#{params[:nome]}%'" unless params[:nome].blank?

    unless params[:titulo].blank?
      conditions << "UPPER(empreendimentos.titulo) LIKE '%#{params[:titulo]}%'"
      @categorias = Categoria.joins(:empreendimentos).where(conditions.join(' AND '))
    else
      @categorias = Categoria.where(conditions.join(' AND '))
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /categorias/1
  def show
    render layout: false
  end

  def new
    @categoria = Categoria.new
  end

  def edit
  end

  # PATCH/PUT /users/1
  def update
      if @categoria.update(categoria_params)
        redirect_to request.referrer, notice: "Categoria atualizada!"
      else
        render :edit
      end
  end

  def create
    @categoria = Categoria.new(categoria_params)

      if @categoria.save
        redirect_to request.referrer, notice: "Categoria Criada!"
      else
        render :new
      end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categoria
      @categoria = Categoria.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def categoria_params
      params.require(:categoria).permit(:nome, :descricao, :ativo)
    end


end

app/views/admin/categorias/_form.html.erb
<%= form_for [:admin, @categoria] do |f| %>

  <div id="form_error">
    <%= render '/shared/form_error', object: @categoria %>
  </div>

  <div class="row">
      <div class="field">
        <div class="input-field col s12">
          <i class="material-icons prefix">format_align_justify</i>
          <%= f.text_field :nome %>
          <label for="icon_prefix">Nome</label>
        </div>
      </div>
      <div class="field">
        <div class="input-field col s12">
          <i class="material-icons prefix">format_align_justify</i>
          <%= f.text_field :descricao, as: :text, class: "materialize-textarea", 'data-length' => "500", id: "textarea1", maxlength: 500 %>
          <label for="textarea1">Descrição</label>
        </div>
      </div>
  </div>
    <div class="switch col s3">
    <div class="title">
      <p>Ativo</p>
    </div>
      <label>
        Não
        <%= f.check_box :ativo, checked: true %>
        <span class="lever"></span>
        Sim
      </label>
    </div>

    <div class="field">
      <div class="input-field col s12">
        <div class="actions">
          <button class="btn waves-effect waves-light" type="submit" name="action">Salvar
            <i class="material-icons right">send</i>
          </button>
        </div>
      </div>
    </div>

<% end %>

<script type="text/javascript">
  $(document).ready(function() {
    $('select').material_select();
  });

  $(document).ready(function() {
    $('input#input_text, textarea#textarea1').characterCounter();
  });
</script>

app/views/admin/categorias/_list.html.erb
  <div id="delay_key" class="progress" style="display: none;">
      <div class="indeterminate"></div>
  </div>

  <table class="highlight">
    <thead>
      <tr>
        <th>#</th>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Imóveis</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <% @categorias.each do |categoria| %>
        <tr>
          <td><%= categoria.id %></td>
          <td><%= categoria.nome %></td>
          <td><%= categoria.descricao %></td>
          <td><%= categoria.produtos.size %></td>
          <td>
            <%= link_to "<i class='material-icons prefix'>edit</i>".html_safe, edit_admin_categoria_path(categoria), class: "btn btn-floating" %>
            <%= link_to "<i class='material-icons prefix'>delete</i>".html_safe, admin_categoria_path(categoria), method: :delete, data: { confirm: "Você tem certeza?" }, class: "btn btn-floating", style: "background-color: red;" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/admin/categorias/edit.html.erb
<div class="container">

    <div class="title">
      <h4>Editar Categoria - <%= @categoria.nome %></h4>
    </div>

    <%= render 'form' %>


</div>

app/views/admin/categorias/index.html.erb
<% content_for(:title, "Categorias") %>

<div class="title">
	<h3><%= "Categorias" %></h3>
</div>
<div style="margin: 15px; padding: 15px;">
	<%= link_to "Nova", new_admin_categoria_path, class: "btn", style: "background-color: #5073b6; color: white;" %>
</div>
  <div class="row">
    <form class="col s12">
      <div class="row">
		<div class="input-field col s2">
		  <input id="id" type="text" class="validate">
		  <label class="active" for="id">Código</label>
		</div>
		<div class="input-field col s2">
		  <input id="nome" type="text" class="validate">
		  <label class="active" for="nome">Nome da Categoria</label>
		</div>
		<div class="input-field col s2">
		  <input id="produto" type="text" class="validate">
		  <label class="active" for="produto">Título do Produto</label>
		</div>
      </div>
    </form>
  </div>

<div class="row">
  <div class="col s12 m12 l12">
    <div id="categoria_list">
      <%= render 'list' %>
    </div>
  </div>

</div>


<script type="text/javascript">

  $(function($) {

    $("#id").keyup(function() {

      if( $(this).prop('value') != "" ) {
        var id = $(this).prop('value');
        var nome = $("#nome").prop('value');
        var titulo = $("#titulo").prop('value');
        delay(function(){
        	att_index(id, nome, titulo);
        }, 1000 );


      }
    });

    $("#nome").keyup(function() {

      if( $(this).prop('value') != "" ) {
        var nome = $(this).prop('value');
        var titulo = $("#titulo").prop('value');
        var id = $("#id").prop('value');
        delay(function(){
        	att_index(id, nome, titulo);
        }, 1000 );


      }
    });

    $("#titulo").keyup(function() {

      if( $(this).prop('value') != "" ) {
        var titulo = $(this).prop('value');
        var id = $("#id").prop('value');
        var nome = $("#nome").prop('value');
        delay(function(){
        	att_index(id, nome, titulo);
        }, 1000 );


      }
    });

  });



</script>

<script type="text/javascript">
  
function att_index(id, nome, titulo){

    $.ajax({
      url: "/admin/categorias",
      method: "GET",
      dataType: "script",
      data: {
      	'id': 			id,
        'nome': 		nome,
        'titulo': 		titulo
      },
    });

}
</script>

<script type="text/javascript">
  var delay = (function(){
    var timer = 0;
    return function(callback, ms){
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
      $("#delay_key").css("display","inherit");
    };
  })();

  $("input").keyup(function() {
    $(this).val($(this).val().toUpperCase());
  });

</script>

app/views/admin/categorias/new.html.erb
<div class="container">

    <div class="title">
      <h4>Nova Categoria</h4>
    </div>

    <%= render 'form' %>


</div>