config/routes.rb
Rails.application.routes.draw do

#=============================================================================
# ================================ ADMIN =====================================
#=============================================================================
  namespace :admin do

    controller :users do
    end
    resources :users

    controller :empreendimentos do
      post '/empreendimentos/deletar_foto/:id' => :deletar_foto, as: :empreendimentos_deletar_foto
    end
    resources :empreendimentos

    controller :categorias do
    end
    resources :categorias

    controller :contatos do
    end
    resources :contatos

    controller :contato_assuntos do
    end
    resources :contato_assuntos

    controller :vagas_pretendidas do
    end
    resources :vagas_pretendidas

    controller :pages do
        get '/home' => :home
    end
    root 'pages#home'
  end

#=============================================================================
# ================================ PÚBLICO ===================================
#=============================================================================

  devise_for :users, :controllers => { registrations: 'registrations',
                                        :omniauth_callbacks => "callbacks" }



  authenticated :user do
    root 'admin/pages#home', as: :authenticated_root
  end

  controller :users do
    post "users/novo_contato" => :novo_contato
  end
  resources :users, only: [:new, :create]

  controller :empreendimentos do
  end
  resources :empreendimentos, only: [:index, :show]

  controller :contatos do
  end
  resources :contatos, only: [:index, :new, :create]

  controller :enderecos do
    post "enderecos/att_endereco" => :att_endereco
  end

  controller :pages do
    get '/home' => :home
    get '/sac' => :sac
    get '/trabalhe_conosco' => :trabalhe_conosco
    get '/dicas' => :dicas
    get '/minha_casa_minha_vida' => :minha_casa_minha_vida
  end 

  root 'pages#home'

end

app/views/admin/shared/_footer.html.erb
<footer style="height: 50px;">
	
</footer>

app/views/admin/shared/_navbar.html.erb
<nav class="nav_top_back">
  <div class="nav-wrapper">
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
                <li><%= link_to("Sair <i class='material-icons'>exit_to_app</i>".html_safe, destroy_user_session_path, :method => :delete, style: "display: inline-flex;") %></li>
              <li>
                <img src="<%= current_user.image_to %>" class="circle" style="padding-top: 5px; max-width: 50px;">
              </li>
        <% end %>
    </ul>

    <ul class="left hide-on-med-and-down">
      <li>
          <a href="#" data-activates="slide-out" class="button-collapse" style="display: inline !important;"><i class='material-icons'>menu</i></a>


          <ul id="slide-out" class="side-nav left-align">
            <li>
              <div class="user-view">
                <div class="background">
                  <img src="/images/banners/office.jpg">
                </div>
                <a><img class="circle" src="<%= current_user.image_to %>"></a>
                <a><span class="white-text name"><%= current_user.name %></span></a>
                <a><span class="white-text email"><%= current_user.email %></span></a>
              </div>
            </li>
            <li>
              <ul class="collapsible collapsible-accordion">
                <li>
                  <a class="collapsible-header"><i class="material-icons">group</i>Devises</a>
                  <div class="collapsible-body">
                    <ul style="display: grid;">
                      <li><%= link_to "Usuários", admin_users_path %></li>
                    </ul>
                  </div>
                </li>
                <li><div class="divider"></div></li>
                <li>
                  <a class="collapsible-header"><i class="material-icons">store</i>Produtos</a>
                  <div class="collapsible-body">
                    <ul style="display: grid;">
                      <li><%= link_to "Empreendimentos", admin_empreendimentos_path %></li>
                      <li><%= link_to "Categorias", admin_categorias_path %></li>
                    </ul>
                  </div>
                </li>
                <li><div class="divider"></div></li>
                <li>
                  <a class="collapsible-header"><i class="material-icons">contact_phone</i>Contatos</a>
                  <div class="collapsible-body">
                    <ul style="display: grid;">
                      <li><%= link_to "SAC", admin_contatos_path(sac: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
                      <li><%= link_to "Trabalhe Conosco", admin_contatos_path(trabalhe_conosco: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
                      <li><%= link_to "Dúvidas e Sugestões", admin_contatos_path(dicas: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
                      <li><%= link_to "Assuntos", admin_contato_assuntos_path %></li>
                      <li><%= link_to "Vagas Pretendidas", admin_vagas_pretendidas_path %></li>
                    </ul>
                  </div>
                </li>
              </ul>
            </li>
            <li><div class="divider"></div></li>
            <li><%= link_to('Sair', destroy_user_session_path, :method => :delete) %></li>
          </ul>
      </li>

      <li>Logado como Administrador</li>
    </ul>
  </div>
</nav>

<nav class="nav_botton_back">
    <div class="nav-wrapper">
        <img class="logo" src="/images/logos/logo.png">
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><%= link_to "HOME", admin_root_path, class: "#{'active' if current_page? admin_root_path}" %></li>
        <li><%= link_to "USUÁRIOS", admin_users_path, class: "#{'active' if current_page? admin_users_path}" %></li>
        <li><%= link_to "EMPREENDIMENTOS", admin_empreendimentos_path, class: "#{'active' if current_page? admin_empreendimentos_path}" %></li>
        <li><%= link_to "SAC", admin_contatos_path(sac: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
        <li><%= link_to "Trabalhe Conosco", admin_contatos_path(trabalhe_conosco: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
        <li><%= link_to "Dúvidas e Sugestões", admin_contatos_path(dicas: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <li><%= link_to "HOME", admin_root_path, class: "#{'active' if current_page? admin_root_path}" %></li>
        <li><%= link_to "USUÁRIOS", admin_users_path, class: "#{'active' if current_page? admin_users_path}" %></li>
        <li><%= link_to "EMPREENDIMENTOS", admin_empreendimentos_path, class: "#{'active' if current_page? admin_empreendimentos_path}" %></li>
        <li><%= link_to "SAC", admin_contatos_path(sac: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
        <li><%= link_to "Trabalhe Conosco", admin_contatos_path(trabalhe_conosco: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
        <li><%= link_to "Dicas", admin_contatos_path(dicas: true), class: "#{'active' if current_page? admin_contatos_path}" %></li>
      </ul>
    </div>
  </nav>